Added routes for rents
wolox-training/lp-rails pull request #15
Opened 2017-08-14 17:50 UTC by lucaspolonuer

2017-08-14 18:11 UTC, trueshizus requested changes

2017-08-14 18:11 UTC, JesusHerrera commented on app/controllers/api/v1/rents_controller.rb
> +        rents = Rent.where(user_id: current_user.id)
Avoid using _id unless is required

2017-08-14 18:11 UTC, JesusHerrera commented on spec/controllers/api/v1/rents_controller_spec.rb
> +      it 'responses with the rent json' do
responds

2017-08-14 18:11 UTC, JesusHerrera commented on Gemfile
> +gem 'sidekiq'
Why is this gem added?

2017-08-14 18:11 UTC, JesusHerrera commented on app/assets/javascripts/api/v1/rents.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
remove unused files

2017-08-14 18:11 UTC, JesusHerrera commented on app/assets/stylesheets/api/v1/rents.scss
> +// Place all the styles related to the Api/V1/Rents controller here.
remove unused files

2017-08-15 15:31 UTC, lucaspolonuer commented
I will solve these in the next PR

2017-08-15 15:31 UTC, merged