Kickoff maquetado main
wolox-training/lp-rails pull request #3
Opened 2017-08-02 14:17 UTC by lucaspolonuer

2017-08-04 20:18 UTC, trueshizus requested changes

2017-08-04 20:18 UTC, JesusHerrera commented on app/views/landing/index.html.erb
> +<p>Find me in app/views/landing/index.html.erb</p>
This file is an erb file, it should be a slim file

2017-08-04 20:18 UTC, JesusHerrera commented on config/routes.rb
> +  get '/', to: 'landing#index', as: 'landing'
Are you sure `, as: 'landing'` is required?

2017-08-05 18:51 UTC, lucaspolonuer commented on app/views/landing/index.html.erb
> +<p>Find me in app/views/landing/index.html.erb</p>
Yes, it was changed in the following branches, will be changing it here too

2017-08-05 18:52 UTC, lucaspolonuer commented on config/routes.rb
> +  get '/', to: 'landing#index', as: 'landing'
it provides a shortcut for accessing this path from anywhere in your code, not necessary now but could be useful later, you think I should remove it?

2017-08-09 18:45 UTC, closed without merging